// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "Stripe",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v11)
    ],
    products: [
        .library(
            name: "Stripe",
            targets: ["Stripe"]
        ),
        .library(
            name: "StripeIdentity",
            targets: ["StripeIdentity"]
        )
    ],
    targets: [
        .target(
            name: "Stripe",
            dependencies: ["Stripe3DS2", "StripeCore", "StripeUICore"],
            path: "Stripe",
            exclude: [
                "Info.plist",
                "STPThreeDSButtonCustomization.swift",
                "STPThreeDSCustomizationSettings.swift",
                "STPThreeDSFooterCustomization.swift",
                "STPThreeDSLabelCustomization.swift",
                "STPThreeDSNavigationBarCustomization.swift",
                "STPThreeDSSelectionCustomization.swift",
                "STPThreeDSTextFieldCustomization.swift",
                "STPThreeDSUICustomization.swift",
                "STPAddressFieldTableViewCell.swift",
                "STPBankSelectionTableViewCell.swift",
                "STPCardScannerTableViewCell.swift",
                "STPPaymentOptionTableViewCell.swift",
                "STPShippingMethodTableViewCell.swift",
                "UITableViewCell+Stripe_Borders.swift",
                "CardDetailsEditView.swift",
                "CardScanningView.swift",
                "CircularButton.swift",
                "PaymentMethodTypeCollectionView.swift",
                "PaymentOption+Images.swift",
                "PaymentSheet.swift",
                "PaymentSheet+SwiftUI.swift",
                "PaymentSheet+API.swift",
                "PaymentSheetConfiguration.swift",
                "PaymentSheetError.swift",
                "PaymentSheetFlowController.swift",
                "PaymentSheetViewController.swift",
                "PaymentSheet+PaymentMethodAvailability.swift",
                "PaymentSheetFormFactory.swift",
                "AfterpayPriceBreakdownView.swift",
                "STP3DS2AuthenticateResponse.swift",
                "ApplePayHeaderView.swift",
                "CheckboxButton.swift",
                "ConfirmButton.swift",
                "ShadowedRoundedRectangleView.swift",
                "SheetNavigationBar.swift",
                "STPAnalyticsClient+PaymentSheet.swift",
                "STPApplePayContext+PaymentSheet.swift",
                "SavedPaymentMethodCollectionView.swift",
                "SavedPaymentOptionsViewController.swift",
                "LoadingViewController.swift",
                "BottomSheet3DS2ViewController.swift",
                "BottomSheetViewController.swift",
                "STPCardFormView+SwiftUI.swift",
                "STPCardFormView.swift",
                "STPMultiFormTextField.swift",
                "STPLabeledFormTextFieldView.swift",
                "STPLabeledMultiFormTextFieldView.swift",
                "STPFormTextFieldContainer.swift",
                "STPAUBECSDebitFormView.swift",
                "AddPaymentMethodViewController.swift",
                "BottomSheet3DS2ViewController.swift",
                "BottomSheetViewController.swift",
                "ChoosePaymentOptionViewController.swift",
                "LoadingViewController.swift",
                "PaymentSheetViewController.swift",
                "STPAddCardViewController.swift",
                "STPBankSelectionViewController.swift",
                "STPCoreScrollViewController.swift",
                "STPCoreTableViewController.swift",
                "STPCoreViewController.swift",
                "STPFakeAddPaymentPassViewController.swift",
                "STPPaymentOptionsInternalViewController.swift",
                "STPPaymentOptionsViewController.swift",
                "STPShippingAddressViewController.swift",
                "STPShippingMethodsViewController.swift",
                "SavedPaymentOptionsViewController.swift",
                "STPPaymentCardTextFieldCell.swift",
                "STPPaymentActivityIndicatorView.swift",
                "STPSectionHeaderView.swift",
                "STPCardScanner.swift",
                "STPCardScannerTableViewCell.swift",
                "STPCardParams.swift",
                "STPCameraView.swift",
                "STPUserInformation.swift",
                "STPPaymentContext.swift",
                "STPPaymentContextAmountModel.swift",
                "UITableViewCell+Stripe_Borders.swift",
                "UIBarButtonItem+Stripe.swift",
                "UINavigationBar+Stripe_Theme.swift",
                "STPTheme.swift",
                "STPAddressViewModel.swift",
                "STPAUBECSFormViewModel.swift",
                "STPSource.swift",
                "STPSourcePoller.swift",
                "STPSourceParams.swift",
                "STPSourceWeChatPayDetails.swift",
                "STPSourceOwner.swift",
                "STPSourceEnums.swift",
                "STPSourceReceiver.swift",
                "STPSourceRedirect.swift",
                "STPSourceVerification.swift",
                "STPSourceCardDetails.swift",
                "STPSourceKlarnaDetails.swift",
                "STPMultipartFormDataEncoder.swift",
                "STPMultipartFormDataPart.swift",
                "STPSourceSEPADebitDetails.swift",
                "STPCustomer.swift",
                "STPCustomerContext.swift",
                "STPBackendAPIAdapter.swift",
                "STPBankAccount.swift",
                "STPBankAccountParams.swift",
                "STPPaymentMethodOXXO.swift",
                "STPPaymentMethodOXXOParams.swift",
                "STPPaymentMethodPayPal.swift",
                "STPPaymentMethodPayPalParams.swift",
                "STPKlarnaLineItem.swift",
                "STPPushProvisioningContext.swift",
                "STPPushProvisioningDetails.swift",
                "STPPushProvisioningDetailsParams.swift",
                "STPPaymentMethodUPI.swift",
                "STPPaymentMethodUPIParams.swift",
                "STPPaymentMethodNetBanking.swift",
                "STPPaymentMethodNetBankingParams.swift",
                "STPPaymentMethodAlipay.swift",
                "STPPaymentMethodAlipayParams.swift",
                "STPPaymentMethodAUBECSDebit.swift",
                "STPPaymentMethodAUBECSDebitParams.swift",
                "STPPaymentMethodBacsDebit.swift",
                "STPPaymentMethodBacsDebitParams.swift",
                "STPPaymentMethodBancontact.swift",
                "STPPaymentMethodBancontactParams.swift",
                "STPPaymentMethodEPS.swift",
                "STPPaymentMethodEPSParams.swift",
                "STPPaymentMethodFPX.swift",
                "STPPaymentMethodFPXParams.swift",
                "STPPaymentMethodGiropay.swift",
                "STPPaymentMethodGiropayParams.swift",
                "STPPaymentMethodGrabPay.swift",
                "STPPaymentMethodGrabPayParams.swift",
                "STPPaymentMethodPrzelewy24.swift",
                "STPPaymentMethodPrzelewy24Params.swift",
                "STPPaymentMethodSEPADebit.swift",
                "STPPaymentMethodSEPADebitParams.swift",
                "STPPaymentMethodSofort.swift",
                "STPPaymentMethodSofortParams.swift",
                "STPPaymentMethodiDEAL.swift",
                "STPPaymentMethodiDEALParams.swift",
                "STPPaymentMethodWeChatPay.swift",
                "STPPaymentMethodWeChatPayParams.swift",
                "STPPaymentMethodAfterpayClearpay.swift",
                "STPPaymentMethodAfterpayClearpayParams.swift",
                "STPPaymentMethodBoleto.swift",
                "STPPaymentMethodBoletoParams.swift",
                "STPPaymentMethodBLIK.swift",
                "STPPaymentMethodBLIKParams.swift",
                "STPRedirectContext.swift",
                "STPAPIClient+PushProvisioning.swift",
                "PKAddPaymentPassRequest+Stripe_Error.swift",
                "STPFPXBankBrand.swift",
                "STPFPXBankStatusResponse.swift",
                "STPIntentActionOXXODisplayDetails.swift",
                "STPPaymentOptionTuple.swift",
                "STPBECSDebitAccountNumberValidator.swift",
                "STPBSBNumberValidator.swift",
                "UINavigationController+Stripe_Completion.swift",
                "UIView+Stripe_SafeAreaBounds.swift",
                "STPIssuingCardPin.swift",
                "STPConfirmAlipayOptions.swift",
                "STPConfirmWeChatPayOptions.swift",
                "STPApplePayPaymentOption.swift",
                "STPEphemeralKey.swift",
                "STPEphemeralKeyManager.swift",
                "STPMandateCustomerAcceptanceParams.swift",
                "STPMandateDataParams.swift",
                "STPMandateOnlineParams.swift",
                "STPConnectAccountAddress.swift",
                "STPConnectAccountCompanyParams.swift",
                "STPConnectAccountIndividualParams.swift",
                "STPConnectAccountParams.swift",
                "STPFile.swift",
                "STPPinManagementService.swift",
                "UIViewController+Stripe_NavigationItemProxy.swift",
                "UIImage+Stripe.swift",
                "UIViewController+Stripe_KeyboardAvoiding.swift",
                "STPAddCardViewController.swift",
                "CheckboxButton.swift",
                "SaveCheckboxElement.swift",
                "PanModal/Animator/PanModalAnimator.swift",
                "PanModal/Animator/PanModalPresentationAnimator.swift",
                "PanModal/Controller/PanModalPresentationController.swift",
                "PanModal/Delegate/PanModalPresentationDelegate.swift",
                "PanModal/Presentable/PanModalHeight.swift",
                "PanModal/Presentable/PanModalPresentable.swift",
                "PanModal/Presentable/PanModalPresentable+Defaults.swift",
                "PanModal/Presentable/PanModalPresentable+LayoutHelpers.swift",
                "PanModal/Presentable/PanModalPresentable+UIViewController.swift",
                "PanModal/Presenter/PanModalPresenter.swift",
                "PanModal/Presenter/UIViewController+PanModalPresenter.swift",
            ],
            resources: [
                .process("Info.plist"),
                .process("Resources/Images"),
                .process("Resources/au_becs_bsb.json")
            ]
        ),
        .target(
            name: "Stripe3DS2",
            path: "Stripe3DS2/Stripe3DS2",
            exclude: ["Info.plist", "Resources/CertificateFiles", "include/Stripe3DS2-Prefix.pch"],
            resources: [
                .process("Info.plist"),
                .process("Resources")
            ]
        ),
        .target(
            name: "StripeCore",
            path: "StripeCore/StripeCore",
            exclude: ["Info.plist"],
            resources: [
                .process("Info.plist")
            ]
        ),
        .target(
            name: "StripeIdentity",
            dependencies: ["StripeCore", "StripeUICore"],
            path: "StripeIdentity/StripeIdentity",
            exclude: ["Info.plist"],
            resources: [
                .process("Info.plist")
            ]
        ),
        .target(
            name: "StripeUICore",
            dependencies: ["StripeCore"],
            path: "StripeUICore/StripeUICore",
            exclude: ["Info.plist"],
            resources: [
                .process("Info.plist"),
                .process("Resources/Images"),
                .process("Resources/JSON")
            ]
        )
    ]
)
